version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: queuing
    container_name: queuing
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    links:
      - mysql
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=queue
      - MYSQL_ROOT_PASSWORD=teste@123
    ports:
      - 3306:3306
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    volumes:
      - /db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  localstack:
    container_name: localstack-with-aws-cli
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge
